branches: [dev, main]

pipeline:
  build:
    image: alpine:edge
    environment:
    - REPO=https://ziglang.org/download/index.json
    commands:
    - apk add curl jq git
    - curl -sL $(curl -sL $REPO | jq -r '.master."x86_64-linux".tarball') | tar xJ
    - ./zig-linux-*/zig build -fno-stage1 -Dtarget=x86_64-linux-musl
